// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Removed dotenv import; using Prisma's env() helper
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
